Add error checking and file guarantee

diff --git a/scripts/regxml_extractor.sh.in b/scripts/regxml_extractor.sh.in
--- a/scripts/regxml_extractor.sh.in
+++ b/scripts/regxml_extractor.sh.in
@@ -167,6 +167,7 @@ if [ $status -ne 0 ]; then
 fi
 
 #Does it look like we ran before?
+touch manifest.txt
 if [ $(ls *hive 2>/dev/null | wc -l) -gt 0 ]; then
   echo "Note: Found some hive files.  Assuming extraction has already run.  If this is wrong, remove *.hive."
 else
@@ -176,6 +177,11 @@ else
   fi
   #Invoke extraction script
   "$PYTHON" "$pkgdatadir/python/rx_extract_hives.py" $maybe_dfxml_flag "$1" >manifest.txt
+  rc=$?
+  if [ $rc -ne 0 ]; then
+    echo "Error: Hive extraction script failed." >&2
+    exit $rc
+  fi
 fi
 
 # For each regxml file generated, run xmllint to validate and pretty-print
