Compact commits made from deployment

diff --git a/scripts/regxml_extractor.sh.in b/scripts/regxml_extractor.sh.in
--- a/scripts/regxml_extractor.sh.in
+++ b/scripts/regxml_extractor.sh.in
@@ -28,23 +28,41 @@
 # NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 # SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.    
 
+PYTHON=@PYTHON@
+prefix=@prefix@
+exec_prefix=@exec_prefix@
+bindir=$exec_prefix/bin
+
 if [ $# -lt 1 ]; then
   echo "Usage: $0 <disk image>" >&2
+  echo "Note that the results are written to the current working directory." >&2
   exit 1
 fi
 
-#If not installed, just run local scripts
-SCRIPT_PREFIX=""
-if test "x$(which rx_extract_hives.py)" = "x" ; then
-  SCRIPT_PREFIX="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/"
+fiout=fiout.dfxml
+#Do we have Fiwalk output?
+if [ ! -f "$fiout" ]; then
+  echo "Did not detect Fiwalk output.  Generating fiout.dfxml."
+  fiwalk -Xfiout.dfxml -f "$1" >fiout.dfxml.1.log 2>fiout.dfxml.2.log
+  status=$?
+  if [ $status -ne 0 ]; then
+    echo "Error in Fiwalk; see fiout.dfxml.2.log.  Resuming, but this may fail." >&2
+    fiout=
+  else
+    fiout=fiout.dfxml
+  fi
 fi
 
 #Does it look like we ran before?
 if [ $(ls *hive 2>/dev/null | wc -l) -gt 0 ]; then
-  echo "Found some hive files.  Assuming extraction has already run.  If this is wrong, remove *.hive"
+  echo "Found some hive files.  Assuming extraction has already run.  If this is wrong, remove *.hive."
 else
+  maybe_dfxml_flag=
+  if [ ! "$fiout" == "" ]; then
+    maybe_dfxml_flag=-x"$fiout"
+  fi
   #Invoke extraction script
-  "${SCRIPT_PREFIX}rx_extract_hives.py" --hivexml "$1" >manifest.txt
+  "$PYTHON" "$bindir/rx_extract_hives.py" $maybe_dfxml_flag --hivexml "$1" >manifest.txt
 fi
 
 # For each regxml file generated, run xmllint to validate and pretty-print
@@ -60,6 +78,6 @@ else
   done
   # When all regxml is pretty-printed, generate a database
   if [ -f linted.txt ]; then
-    "${SCRIPT_PREFIX}rx_make_database.py" linted.txt manifest.txt out.sqlite
+    "$PYTHON" "$bindir/rx_make_database.py" linted.txt manifest.txt out.sqlite
   fi
 fi
