Add TSK DB and Fiwalk merge

diff --git a/scripts/regxml_extractor.sh.in b/scripts/regxml_extractor.sh.in
--- a/scripts/regxml_extractor.sh.in
+++ b/scripts/regxml_extractor.sh.in
@@ -62,6 +62,18 @@ if [ $status -ne 0 ]; then
   exit 1
 fi
 
+tskout=tskout.db
+#Generate TSK database output
+tsk_loaddb -d tskout.db "$1" >tskout.db.out.log 2>tskout.db.err.log
+status=$?
+if [ $status -ne 0 ]; then
+  echo "Error: tsk_loaddb: see tskout.db.err.log.  Continuing without TSK output."
+  tskout=
+fi
+
+#Make Fiwalk lookup database
+$PYTHON /Users/ajnelson/local/src/regxml_extractor/deps/dfxml/python/verify_fiwalk_versus_tsk_db.py $fiout $tskout fiwalk_lookup.db >fiwalk_lookup.db.out.log 2>fiwalk_lookup.db.err.log
+
 #Does it look like we ran before?
 if [ $(ls *hive 2>/dev/null | wc -l) -gt 0 ]; then
   echo "Note: Found some hive files.  Assuming extraction has already run.  If this is wrong, remove *.hive."
